# ALSA configuration for DevTerm CM3 (ES8388 via I2S)

pcm.!default {
    type asym
    playback.pcm {
        type plug
        slave.pcm "hw:DevTerm,0"
    }
    capture.pcm {
        type plug
        slave.pcm "hw:DevTerm,0"
    }
}

ctl.!default {
    type hw
    card DevTerm
}
